export const routes = {
  startPage: "/",
  auth: "/auth",
  loginTransition: "/loading",
  user: "/userProfile/:id",
  editProfile: "/editProfile",
  news: "/news",
  albums: "/albums",
  album: "/album/:id",
  albumCreator: "/albumCreator",
  groups: "/groups",
  group: "/group/:id",
  groupAlbum: "/groupAlbum/:id",
  groupCreator: "/groupCreator",
  groupAlbumCreator: "/groupAlbumCreator",
  search: "/search",
  notFound: "/notFound",
  albumNotLogged: "/albumPreview/:id",
};
